// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {manager} from '../models';

export function AddUser(arg1:any):Promise<app.Response>;

export function DelUser(arg1:string):Promise<app.Response>;

export function GetConfig():Promise<app.Response>;

export function Greet(arg1:string):Promise<string>;

export function ListUser():Promise<Array<manager.Display>>;
