// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUser(arg1) {
  return window['go']['app']['App']['AddUser'](arg1);
}

export function DelUser(arg1) {
  return window['go']['app']['App']['DelUser'](arg1);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function ListUser() {
  return window['go']['app']['App']['ListUser']();
}
