// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {manager} from '../models';

export function Greet(arg1:string):Promise<string>;

export function ListUser():Promise<Array<manager.Display>>;
